# Generated by Django 2.0.2 on 2018-10-09 18:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Создал заявку')),
                ('sender_email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('passenger', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('vessel', models.CharField(max_length=100, verbose_name='Т/х')),
                ('service_dates', models.CharField(max_length=100, verbose_name='Даты обслуживания')),
            ],
        ),
    ]
