# Generated by Django 2.0.2 on 2018-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourtickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttorder',
            name='passenger_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во пассажиров'),
        ),
    ]
