# Generated by Django 2.0.2 on 2018-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourtickets', '0002_ttorder_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ttorder',
            name='tt_number',
            field=models.IntegerField(default=0, verbose_name='Номер туртикета'),
        ),
    ]
