# Generated by Django 2.0.2 on 2018-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourtickets', '0003_auto_20181010_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttorder',
            options={'ordering': ('-pk',)},
        ),
    ]
