# Generated by Django 2.0.2 on 2018-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourtickets', '0006_auto_20181010_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttorder',
            name='arrival_date',
            field=models.CharField(default=0, max_length=100, verbose_name='Дата прибытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttorder',
            name='program',
            field=models.CharField(default=0, max_length=500, verbose_name='Программа пребывания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ttorder',
            name='vessel',
            field=models.CharField(max_length=100, verbose_name='Название корабля'),
        ),
    ]
