# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170802_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Read')], default=1, verbose_name='Стутус сообщения'),
        ),
    ]
