# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='status',
        ),
    ]
