# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20170830_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_admin',
        ),
    ]
