# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20171228_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
