# Generated by Django 2.0.2 on 2018-02-18 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20171228_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.ChatRoom'),
        ),
    ]
