# Generated by Django 2.0.2 on 2018-03-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20180218_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
