# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0002_auto_20170517_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museums.Museum'),
        ),
    ]
