# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0003_auto_20170517_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Конец'),
        ),
    ]
