# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0004_auto_20170518_1659'),
        ('museums', '0002_auto_20170517_1940'),
    ]

    operations = [
    ]
