# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0005_merge_20170519_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='accompanying_guide',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='audioguide',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='max_count',
        ),
        migrations.AddField(
            model_name='museum',
            name='accompanying_guide_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость сопровождающего гида'),
        ),
        migrations.AddField(
            model_name='museum',
            name='audioguide_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость аудиогида'),
        ),
        migrations.AddField(
            model_name='museum',
            name='full_coefficient',
            field=models.IntegerField(default=0, verbose_name='Коэффициент стоимости для взрослого билета'),
        ),
        migrations.AddField(
            model_name='museum',
            name='fullticket_price',
            field=models.IntegerField(default=0, verbose_name='Взрослый билет, цена'),
        ),
        migrations.AddField(
            model_name='museum',
            name='reduce_coefficient',
            field=models.IntegerField(default=0, verbose_name='Коэффициент стоимости для льготного билета'),
        ),
        migrations.AddField(
            model_name='museum',
            name='reduceticket_price',
            field=models.IntegerField(default=0, verbose_name='Льготный билет, цена'),
        ),
    ]
