# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0006_auto_20170606_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='accompanying_guide_price',
            field=models.IntegerField(default=0, verbose_name='Цена сопровождающего гида'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='audioguide_price',
            field=models.IntegerField(default=0, verbose_name='Цена аудиогоида'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='full_coefficient',
            field=models.FloatField(default=0.0, verbose_name='Коэфф. стоимости взрослого'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='fullticket_price',
            field=models.IntegerField(default=0, verbose_name='Цена взрослый'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='reduce_coefficient',
            field=models.FloatField(default=0.0, verbose_name='Коэфф. стоимости льготного'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='reduceticket_price',
            field=models.IntegerField(default=0, verbose_name='Цена льготный'),
        ),
    ]
