# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0009_auto_20170606_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='max_count',
            field=models.IntegerField(default=0, verbose_name='Макс. кол-во человек в группе'),
        ),
    ]
