# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0010_museum_max_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='max_count_full',
            new_name='full_count',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='max_count_reduce',
            new_name='reduce_count',
        ),
        migrations.AddField(
            model_name='schedule',
            name='coefficient_string',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
