# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0011_auto_20170710_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='coefficient_string',
            new_name='full_coefficient_string',
        ),
        migrations.AddField(
            model_name='schedule',
            name='reduce_coefficient_string',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
