# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0012_auto_20170710_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='full_coefficient',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='reduce_coefficient',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='full_coefficient_string',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Коэфф. стоимости взрослого'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reduce_coefficient_string',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Коэфф. стоимости льготного'),
        ),
    ]
