# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('museums', '0013_auto_20170710_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='chat_room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
        ),
    ]
