# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0014_auto_20170728_2350'),
        ('museums', '0014_museum_chat_room'),
    ]

    operations = [
    ]
