# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0015_merge_20170830_1224'),
        ('museums', '0015_merge_20170830_0418'),
    ]

    operations = [
    ]
