# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0015_auto_20170720_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2015, 1, 1), verbose_name='Дата'),
        ),
    ]
