# Generated by Django 2.0.2 on 2018-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0016_merge_20170830_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='contract_number',
            field=models.CharField(default=0, max_length=15, verbose_name='Номер договора'),
            preserve_default=False,
        ),
    ]
