# Generated by Django 2.0.2 on 2018-10-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0017_museum_contract_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museum',
            options={'ordering': ('pk',)},
        ),
    ]
