# Generated by Django 2.0.2 on 2018-10-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0018_auto_20181018_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='contract_number',
        ),
    ]
