# Generated by Django 2.0.2 on 2018-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0019_remove_museum_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_number',
            field=models.CharField(default=22102018, max_length=15, verbose_name='Номер договора'),
            preserve_default=False,
        ),
    ]
