# Generated by Django 2.0.2 on 2018-10-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0020_company_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='voucher_numbers',
            field=models.CharField(default=-100000, max_length=30, verbose_name='Диапазон номеров ваучеров'),
            preserve_default=False,
        ),
    ]
