# Generated by Django 2.0.2 on 2018-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0021_museum_voucher_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='info@avangard-travel.ru', max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='(812) 640-02-28', max_length=30, verbose_name='Номер телефона'),
        ),
    ]
