# Generated by Django 2.0.2 on 2018-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PcOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Создал заявку')),
                ('sender_email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date', models.CharField(max_length=100, verbose_name='Создал заявку')),
                ('passport', models.CharField(max_length=100, verbose_name='Паспортные данные')),
                ('car_mark', models.CharField(max_length=100, verbose_name='Марка транспортного средства')),
                ('car_plates', models.CharField(max_length=100, verbose_name='Государственные регистрационные знаки')),
                ('vessel', models.CharField(max_length=100, verbose_name='Название корабля')),
                ('arrival_date', models.CharField(max_length=100, verbose_name='Дата прибытия')),
                ('tt_number', models.IntegerField(default=0, verbose_name='Номер туртикета')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed')], default=1, verbose_name='Статус')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
