# Generated by Django 2.0.2 on 2018-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxycard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcorder',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата рождения'),
        ),
    ]
