# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museums', '0009_auto_20170606_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullticket_count', models.IntegerField(default=0, verbose_name='Количество взрослых билетов')),
                ('reduceticket_count', models.IntegerField(default=0, verbose_name='Количество льготных билетов')),
                ('audioguide', models.BooleanField(default=False, verbose_name='Аудиогид')),
                ('accompanying_guide', models.BooleanField(default=False, verbose_name='Сопровождающий гид')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('chat_id', models.IntegerField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Purchased')], default=1, verbose_name='Статус')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='Электроная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('museum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museums.Museum')),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museums.Schedule')),
            ],
        ),
    ]
