# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
