# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170704_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
