# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170610_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
    ]
