# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0010_museum_max_count'),
        ('orders', '0004_auto_20170702_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museums.Company'),
        ),
    ]
