# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_company'),
        ('orders', '0004_order_user_id'),
    ]

    operations = [
    ]
