# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20170707_1644'),
        ('orders', '0006_merge_20170710_1334'),
    ]

    operations = [
    ]
