# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 21:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_company'),
    ]

    operations = [

    ]
