# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170729_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullticket_store',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='reduceticket_store',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullticket_count',
            field=models.IntegerField(default=0, verbose_name='Количество взрослых билетов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reduceticket_count',
            field=models.IntegerField(default=0, verbose_name='Количество льготных билетов'),
        ),
    ]
