# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 07:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170805_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullticket_store',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='reduceticket_store',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
        ),
    ]
