# Generated by Django 2.0.2 on 2018-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20170805_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Purchased'), (4, 'Deny'), (5, 'Scanned')], default=1, verbose_name='Статус'),
        ),
    ]
