# Generated by Django 2.0.2 on 2018-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180218_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.FileField(blank=True, upload_to='qr_code'),
        ),
    ]
