# Generated by Django 2.0.2 on 2018-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.CharField(max_length=100, verbose_name='QR code'),
        ),
    ]
