# Generated by Django 2.0.2 on 2018-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180314_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='QR code'),
        ),
    ]
