# Generated by Django 2.0.2 on 2018-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20181018_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ваучер'),
        ),
    ]
