# Generated by Django 2.0.2 on 2018-10-24 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20181024_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='superorder',
            name='orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[0], verbose_name='Номер заказа'), default=[0], size=None),
            preserve_default=False,
        ),
    ]
