# Generated by Django 2.0.2 on 2018-10-24 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_superorder_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superorder',
            old_name='voucher',
            new_name='voucher_path',
        ),
        migrations.AddField(
            model_name='superorder',
            name='voucher_id',
            field=models.IntegerField(default=0, verbose_name='Номер ваучера'),
        ),
        migrations.AlterField(
            model_name='superorder',
            name='orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Номер заказа'), size=None),
        ),
    ]
