# Generated by Django 2.0.2 on 2018-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20181218_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='superorder',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='superorder',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Начало'),
        ),
    ]
