# Generated by Django 2.0.2 on 2018-12-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0022_auto_20181023_1236'),
        ('orders', '0032_auto_20181219_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='superorder',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museums.Museum'),
        ),
    ]
