# Generated by Django 2.0.2 on 2018-12-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_superorder_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='superorder',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Конец'),
        ),
    ]
