# Generated by Django 2.0.2 on 2018-12-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_superorder_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='superorder',
            name='totalPrice',
            field=models.IntegerField(blank=True, default=1000),
            preserve_default=False,
        ),
    ]
