INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can add site', 7, 'add_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can change site', 7, 'change_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can delete site', 7, 'delete_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can add Token', 8, 'add_token');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can change Token', 8, 'change_token');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can delete Token', 8, 'delete_token');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add email address', 9, 'add_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change email address', 9, 'change_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete email address', 9, 'delete_emailaddress');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can add email confirmation', 10, 'add_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can change email confirmation', 10, 'change_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can delete email confirmation', 10, 'delete_emailconfirmation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can add user profile', 11, 'add_userprofile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can change user profile', 11, 'change_userprofile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can delete user profile', 11, 'delete_userprofile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can add museum', 12, 'add_museum');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can change museum', 12, 'change_museum');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can delete museum', 12, 'delete_museum');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add schedule', 13, 'add_schedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change schedule', 13, 'change_schedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete schedule', 13, 'delete_schedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can add company', 14, 'add_company');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can change company', 14, 'change_company');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can delete company', 14, 'delete_company');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can add order', 15, 'add_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can change order', 15, 'change_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can delete order', 15, 'delete_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can add chat room', 16, 'add_chatroom');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can change chat room', 16, 'change_chatroom');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can delete chat room', 16, 'delete_chatroom');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add message', 17, 'add_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change message', 17, 'change_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete message', 17, 'delete_message');